#!/bin/bash
path="${HOME}/.local/state/soccer"
match_file="${path}/match"
data_file="${path}/ger2_data"

mkdir -p ${path}
[ ! -f "${match_file}" ] && touch $match_file

match_id=$(cat $match_file)

match_selected() {
	grep -q '[^[:space:]]' < "${match_file}" && return 0
	return 1
}

valid_match_id () {
	if jq -e ".\"${match_id}\"" $data_file > /dev/null; then
		return 0
	else
		return 1
	fi
}

print_match_info() {
	! match_selected && return 1
	! valid_match_id && return 1

	data=$(jq ".\"${match_id}\"" $data_file)

	team1_score=$(echo "$data" | jq -r '.competitors[0].score')
	team1_abbr=$(echo "$data" | jq -r '.competitors[0].abbrName')
	team2_score=$(echo "$data" | jq -r '.competitors[1].score')
	team2_abbr=$(echo "$data" | jq -r '.competitors[1].abbrName')
	time=$(echo "$data" | jq -r '.time')
	echo "${time} | ${team1_abbr} ${team1_score} : ${team2_score} ${team2_abbr}"
	exit 0
}

if [[ $1 == "is_active" ]]; then
	match_selected && valid_match_id
else
	print_match_info
fi
exit $?
