#!/bin/bash
rdir="${HOME}/.config/rofi/"
refresh_data_script="${HOME}/.local/share/soccer/update_soccer_data"
sdir="${HOME}/.local/state/soccer"
match_file="${sdir}/match"
data_file="${sdir}/ger2_data"

declare -A status_texts
status_texts["STATUS_FIRST_HALF"]=" "
status_texts["STATUS_HALFTIME"]=" "
status_texts["STATUS_SECOND_HALF"]=" "
status_texts["STATUS_FULL_TIME"]="󰃯 "
status_texts["STATUS_SCHEDULED"]="󰃰 "

mkdir -p ${sdir}
[ ! -f "${match_file}" ] && touch $match_file

if test `find "${data_file}" -mmin +1`; then
	"${refresh_data_script}" force-refresh
fi

rofi_list=""
match_ids=()
while read -r entry; do
    match_ids+=($(echo "$entry" | jq -r '.key'))

    status=$(echo "$entry" | jq -r '.value.status')
    time=$(echo "$entry" | jq -r '.value.time')
    team1_name=$(echo "$entry" | jq -r '.value.competitors[0].shortName')
    team1_score=$(echo "$entry" | jq -r '.value.competitors[0].score')
    team2_name=$(echo "$entry" | jq -r '.value.competitors[1].shortName')
    team2_score=$(echo "$entry" | jq -r '.value.competitors[1].score')

    entry_name="${status_texts["${status}"]}\t${time}\t${team1_score} : ${team2_score}\t${team1_name} - ${team2_name}"
    rofi_list+="|${entry_name}"
done < <(jq -c 'to_entries[]' "$data_file")

rofi_list="${rofi_list#'|'}"

sel="$(echo -e ${rofi_list} | rofi -sep '|' -format 'i' -dmenu -markup-rows -theme "${rdir}/styles/select_match.rasi")"

if [[ "${sel}" != "-1" && -n "${sel}" ]]; then
    echo ${match_ids[${sel}]} > $match_file
else
    echo "" > $match_file
fi
