background {
	monitor = 
	path = /home/kaffeekind/Pictures/lockscreen.jpg
	blur_passes = 1
	blur_size = 2
	noise = 0.1
	contrast = 0.9
}

input-field {
	monitor = 
	size = 320, 50
	position = 0, -450
	halign = center
	placeholder_text = 
	inner_color = rgba(f794f7ff)
	rounding = 0
}
