#!/bin/bash
dir="$HOME/.config/rofi/styles"
wp_status=$(wpctl status | awk '/Sinks:/{flag=1;next}/Sources:/{flag=0}flag')

function parse_sinks() {
    # remove symbols | and * and [vol *] bracket
    options=$(echo "${1}" | sed -E 's/│|\*|\[.*\]//g')
    # remove white spaces
    options=$(echo "${options}" | sed -E 's/^[[:space:]]*//g')
    options=$(echo "${options}" | sed -E 's/[[:space:]]*$//g')
    # remove hdmi/display options as audio out
    options=$(echo "${options}" | grep -iv 'hdmi')
    # make id array
    ids=($(echo "${options}" | awk '{ print $1 }' | sed 's/\.//g'))
    sinks=$(echo "${options}" | sed -E 's/^[0-9]+\.[[:space:]]//g')
    sinks=$(echo "${sinks}" | tr '\n' '|')
    if [[ "${sinks: -1}" == "|" ]]; then
	sinks=${sinks%?}
    fi
}

function get_cur_index() {
    local cur_id=$(echo "${1}" | sed -n 's/.*\*[[:space:]]*\([0-9]\+\).*/\1/p')
    
    for i in  "${!ids[@]}"; do
	if [[ "${ids[$i]}" = "${cur_id}" ]]; then
	    echo "$i"
	    break
	fi
    done
    
}

parse_sinks "${wp_status}"
sel_index=$(get_cur_index "${wp_status}")

sel=$(echo -e "${sinks}" | rofi -selected-row ${sel_index} -format 'i' -sep '|' -dmenu -i -theme "$dir/audio_out_dialog.rasi")
if [[ "${sel}" != "-1" && -n "${sel}" ]]; then
    coproc ( wpctl set-default ${ids[${sel}]} )
fi
